name: Notify discord
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Notify on incident creation
        if: ${{ contains(github.event.commits[0].message, 'Create incident') }}
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "Infrastructure Updates"
          embed-title	: "IntellectualSites' Infrastructure Notification"
          avatar-url: "https://raw.githubusercontent.com/IntellectualSites/Assets/main/IntellectualSites.png"
          embed-color: "16711680"
          embed-description: |
           * **An incident has been created**: ${{ github.event.commits[0].message }}
           https://intellectualsites.github.io/infra-status/
      
      - name: Notify on incident update
        if: ${{ contains(github.event.commits[0].message, 'Update incident') }}
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "Infrastructure Updates"
          embed-title	: "IntellectualSites' Infrastructure Notification"
          avatar-url: "https://raw.githubusercontent.com/IntellectualSites/Assets/main/IntellectualSites.png"
          embed-color: "16746496"
          embed-description: |
            **An incident has been updated**: ${{ github.event.commits[0].message }}
            https://intellectualsites.github.io/infra-status/

      - name: Notify on incident resolve
        if: ${{ contains(github.event.commits[0].message, 'Resolve incident') }}
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "Infrastructure Updates"
          embed-title	: "IntellectualSites' Infrastructure Notification"
          avatar-url: "https://raw.githubusercontent.com/IntellectualSites/Assets/main/IntellectualSites.png"
          embed-color: "65280"
          embed-description: |
            **An incident has been resolved**: ${{ github.event.commits[0].message }}
            https://intellectualsites.github.io/infra-status/